#!/bin/sh
# Yes, that's POSIX sh, not bash!

tmpnam=`mktemp`

# Create a one-meg device
dd if=/dev/zero of=$tmpnam bs=1024 count=1024

./nbd-server -C /dev/null -p ./nbd-server.pid 11111 $tmpnam &
sleep 1
./nbd-tester-client localhost 11111
retval=$?
kill `cat nbd-server.pid`
rm -f nbd-server.pid
exit $retval
