#!/bin/sh

set -x

echo 'deb http://us.archive.ubuntu.com/ubuntu wily main' > /etc/apt/sources.list.d/automake.list
cat /etc/apt/sources.list.d/automake.list
(
  echo 'Package: *'
  echo 'Pin: release a=wily'
  echo 'Pin-Priority: 200'
) > /etc/apt/preferences.d/automake.pref
cat /etc/apt/preferences.d/automake.pref
